language: php
php:
- '7.1'
script: phpunit tests
branches:
  only:
  - dev
deploy:
  skip_cleanup: true
  provider: script
  script: _scripts/deploy.sh
  on:
    all_branches: true
notifications:
  email: false
